
services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5